version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        circleci-project-setup

    steps:
      - add_ssh_keys:
          fingerprints:
            - "xx"
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          command: echo build is ok...
          