version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        circleci-project-setup
      ignore:
        gh-pages

    steps:
      - run:
          name: ECHO_DEPLOY_KEY
          command: echo ${DEPLOY_KEY}
      - add_ssh_keys:
          fingerprints:
            - ${DEPLOY_KEY}
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy page
          command: ./deploy.sh
          