version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        circleci-project-setup
      ignore:
        gh-pages

    steps:
      - run:
          name: ECHO_DEPLOY_KEY
          command: echo ${DEPLOY_KEY}
      - add_ssh_keys:
          fingerprints:
            - "54:e5:aa:d4:d9:ad:f4:0d:f0:9b:0a:db:dd:8e:15:5f"
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy page
          command: chmod +x ./deploy.sh && ./deploy.sh
          